version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - mysql-jwt-data:/var/lib/mysql


volumes:
  mysql-jwt-data:

